# ===============================
# SPRING APPLICATION
# ===============================
spring.application.name=safezone

# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/SafeZone
spring.datasource.username=usuario
spring.datasource.password=usuario123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# NETWORK AS CODE API
# ===============================
network.as.code.api.url=https://network-as-code.example.com
network.as.code.token=your-application-key-here
