# ===============================
# SERVER
# ===============================
server.port=8090
spring.application.name=SafeZone

# ===============================
# ORACLE DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=C##RECIPE
spring.datasource.password=recipe
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# NETWORK AS CODE API - SIM SWAP
# ===============================
network.as.code.api.url=https://network-as-code.p-eu.rapidapi.com/passthrough/camara/v1/sim-swap
network.as.code.token=7824879d1fmshb119c865abc4f6dp1e1091jsn523465580504
network.as.code.rapidapi.host=network-as-code.p-eu.rapidapi.com
network.as.code.rapidapi.key=7824879d1fmshb119c865abc4f6dp1e1091jsn523465580504
network.as.code.mock.enabled=false

# ===============================
# LOCATION VERIFICATION API
# ===============================
location.verification.api.url=https://network-as-code.p-eu.rapidapi.com/location-verification/v1
location.verification.token=7824879d1fmshb119c865abc4f6dp1e1091jsn523465580504
location.verification.rapidapi.host=network-as-code.p-eu.rapidapi.com
location.verification.rapidapi.key=7824879d1fmshb119c865abc4f6dp1e1091jsn523465580504
location.verification.mock.enabled=false

# ===============================
# LOGGING
# ===============================
logging.level.com.talenArena.SafeZone.service=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG
logging.level.reactor.netty.http.client=DEBUG

# ===============================
# SWAGGER / API DOCS
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

