# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8090

# ===============================
# DATABASE CONFIGURATION (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/SafeZone
spring.datasource.username=usuario
spring.datasource.password=usuario123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schema.sql

# ===============================
# NETWORK AS CODE API CONFIGURATION
# ===============================
network.as.code.api.url=https://network-as-code.p-eu.rapidapi.com/location-verification/v1/verify
network.as.code.token=14ab4b034dmsha461a78fd955aecp11b124jsnbcd93cea4dc1
network.as.code.rapidapi.host=network-as-code.nokia.rapidapi.com
network.as.code.rapidapi.key=14ab4b034dmsha461a78fd955aecp11b124jsnbcd93cea4dc1
network.as.code.mock.enabled=true

# ===============================
# SWAGGER / API DOCS
# ===============================
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false