# ===============================
# SERVER
# ===============================
server.port=8090

# ===============================
# POSTGRESQL DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/safezonedb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Dualiza687
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===============================
# NETWORK AS CODE API
# ===============================
network.as.code.api.url=https://network-as-code.p-eu.rapidapi.com
network.as.code.token=7824879d1fmshb119c865abc4f6dp1e1091jsn523465580504

# ===============================
# NETWORK AS CODE API MOCK
# ===============================
network.as.code.mock.enabled=false

